-- COMERCIAL --

DROP TABLE IF EXISTS "SaleOrder" CASCADE;
DROP TABLE IF EXISTS "PurchaseOrder" CASCADE;
DROP TABLE IF EXISTS "OutputOrder" CASCADE;
DROP TABLE IF EXISTS "InputOrder" CASCADE;
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "OutputMacro" CASCADE;
DROP TABLE IF EXISTS "InputMacro" CASCADE;
DROP TABLE IF EXISTS "Macro" CASCADE;
DROP TABLE IF EXISTS "FiscalDocumentType" CASCADE;

-- FINANCEIRO --

DROP TABLE IF EXISTS "ReceiptCondition" CASCADE;
DROP TABLE IF EXISTS "PaymentCondition" CASCADE;
DROP TABLE IF EXISTS "ConditionDay" CASCADE;
DROP TABLE IF EXISTS "Condition" CASCADE;

-- ENGENHARIA DE PRODUTOS E SERVICOS --

DROP TABLE IF EXISTS "ProductPart" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "ProductFinish" CASCADE;
DROP TABLE IF EXISTS "ProductDetail" CASCADE;
DROP TABLE IF EXISTS "ProductModel" CASCADE;
DROP TABLE IF EXISTS "ProductLine" CASCADE;
DROP TABLE IF EXISTS "ProductMark" CASCADE;
DROP TABLE IF EXISTS "ProductGroup" CASCADE;
DROP TABLE IF EXISTS "Progeny" CASCADE;
DROP TABLE IF EXISTS "ProgenyType" CASCADE;
DROP TABLE IF EXISTS "MeasureUnitConversion" CASCADE;
DROP TABLE IF EXISTS "MeasureUnit" CASCADE;
DROP TABLE IF EXISTS "MeasureUnitGroup" CASCADE;
DROP TABLE IF EXISTS "IcmsRule" CASCADE;
DROP TABLE IF EXISTS "Icms" CASCADE;
DROP TABLE IF EXISTS "IcmsCst" CASCADE;
DROP TABLE IF EXISTS "IcmsCsosn" CASCADE;
DROP TABLE IF EXISTS "IpiRule" CASCADE;
DROP TABLE IF EXISTS "Ipi" CASCADE;
DROP TABLE IF EXISTS "IpiCst" CASCADE;
DROP TABLE IF EXISTS "PisCofinsRule" CASCADE;
DROP TABLE IF EXISTS "PisCofins" CASCADE;
DROP TABLE IF EXISTS "PisCst" CASCADE;
DROP TABLE IF EXISTS "CofinsCst" CASCADE;

-- FISCAL --

DROP TABLE IF EXISTS "OutputCfop" CASCADE;
DROP TABLE IF EXISTS "InputCfop" CASCADE;
DROP TABLE IF EXISTS "Cfop" CASCADE;

-- GESTAO DE PESSOAS --

DROP TABLE IF EXISTS "Ie" CASCADE;
DROP TABLE IF EXISTS "Rg" CASCADE;
DROP TABLE IF EXISTS "Cpf" CASCADE;
DROP TABLE IF EXISTS "Cnpj" CASCADE;
DROP TABLE IF EXISTS "Address" CASCADE;
DROP TABLE IF EXISTS "City" CASCADE;
DROP TABLE IF EXISTS "State" CASCADE;
DROP TABLE IF EXISTS "Country" CASCADE;
DROP TABLE IF EXISTS "SystemPersonSystemCompany" CASCADE;
DROP TABLE IF EXISTS "SystemPersonSystemAction" CASCADE;
DROP TABLE IF EXISTS "SystemPersonPreference" CASCADE;
DROP TABLE IF EXISTS "SystemAction" CASCADE;
DROP TABLE IF EXISTS "SystemPerson" CASCADE;
DROP TABLE IF EXISTS "SystemCompany" CASCADE;
DROP TABLE IF EXISTS "Company" CASCADE;
DROP TABLE IF EXISTS "Person" CASCADE;
DROP TABLE IF EXISTS "Subject" CASCADE;
DROP TABLE IF EXISTS "Idiom" CASCADE;
DROP TABLE IF EXISTS "Organization" CASCADE;
DROP TABLE IF EXISTS "Cnae" CASCADE;
DROP TABLE IF EXISTS "Rule" CASCADE;
